name: Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: just
      - name: Install tytanic
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tytanic
          git: https://github.com/tingerrr/tytanic.git
      - uses: typst-community/setup-typst@v4
        with:
          typst-version: 'v0.13.1'
      - run: |
          mkdir -p ~/.local/share/typst/packages/preview/cetz
          git clone --depth 1 --branch v0.3.4 https://github.com/cetz-package/cetz.git ~/.local/share/typst/packages/preview/cetz/0.3.4
      - run: |
          just install @local
          just install @preview
          just manual
          just test
